package com.javarevolutions.jhs.persistence;
// Generated Mar 14, 2017 9:05:29 AM by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private int matricula;
     private Login login;
     private String nombre;
     private String app;
     private String apm;
     private Integer edad;
     private String sexo;

    public Alumnos() {
    }

	
    public Alumnos(int matricula) {
        this.matricula = matricula;
    }
    public Alumnos(int matricula, Login login, String nombre, String app, String apm, Integer edad, String sexo) {
       this.matricula = matricula;
       this.login = login;
       this.nombre = nombre;
       this.app = app;
       this.apm = apm;
       this.edad = edad;
       this.sexo = sexo;
    }
   
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public Login getLogin() {
        return this.login;
    }
    
    public void setLogin(Login login) {
        this.login = login;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApp() {
        return this.app;
    }
    
    public void setApp(String app) {
        this.app = app;
    }
    public String getApm() {
        return this.apm;
    }
    
    public void setApm(String apm) {
        this.apm = apm;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }




}


